---
- name: PKI Facts Test
  hosts: datacenter
  gather_facts: true
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: "Gather Facts"
      sonic_facts:
        gather_subset: min
        gather_network_resources:
          - pki
      register: result

    - name: "debug facts"
      debug:
        msg: "{{ result.ansible_facts.ansible_network_resources }}"

- name: PKI Merge Config
  hosts: datacenter
  gather_facts: false
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: "Merge"
      sonic_pki:
        state: merged
        config:
          trust-stores:
            - name: a
              config:
                - ca-name:
                    - CAcert.crt
          security-profiles:
            - profile-name: EricProf
              config:
                - revocation-check: true
                  key-usage-check: false
                  certificate-name: server.crt
#- name: PKI Delete Config
#  hosts: datacenter
#  gather_facts: false
#  connection: httpapi
#  collections:
#    - dellemc.enterprise_sonic
#  tasks:
#    - name: "Delete"
#      sonic_pki:
#        state: deleted
